# This is the only docker-compose file you need for manual testing.
services:
  registry:
    build: .
    container_name: overlay-registry
    command: java -cp /app csx55.overlay.node.Registry 8080
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    networks:
      - overlay-net

  node-1:
    build: .
    container_name: overlay-node-1
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  # ... (definitions for node-2 through node-9 are similar) ...

  node-2:
    build: .
    container_name: overlay-node-2
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-3:
    build: .
    container_name: overlay-node-3
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-4:
    build: .
    container_name: overlay-node-4
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-5:
    build: .
    container_name: overlay-node-5
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-6:
    build: .
    container_name: overlay-node-6
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-7:
    build: .
    container_name: overlay-node-7
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-8:
    build: .
    container_name: overlay-node-8
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-9:
    build: .
    container_name: overlay-node-9
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

  node-10:
    build: .
    container_name: overlay-node-10
    command: java -cp /app csx55.overlay.node.MessagingNode registry 8080
    stdin_open: true
    tty: true
    depends_on:
      - registry
    networks:
      - overlay-net

networks:
  overlay-net:
    driver: bridge