# Override for interactive testing - allows manual startup of Java applications
# Usage: docker-compose up -d, then docker-compose exec <service> bash
services:
  registry:
    command: bash
    stdin_open: true
    tty: true

  node-1:
    command: bash
    stdin_open: true
    tty: true

  node-2:
    command: bash
    stdin_open: true
    tty: true

  node-3:
    command: bash
    stdin_open: true
    tty: true

  node-4:
    command: bash
    stdin_open: true
    tty: true

  node-5:
    command: bash
    stdin_open: true
    tty: true

  node-6:
    command: bash
    stdin_open: true
    tty: true

  node-7:
    command: bash
    stdin_open: true
    tty: true

  node-8:
    command: bash
    stdin_open: true
    tty: true

  node-9:
    command: bash
    stdin_open: true
    tty: true

  node-10:
    command: bash
    stdin_open: true
    tty: true