version: '3.8'

services:
  registry:
    build: .
    container_name: overlay-registry
    # command: ... <--- THIS LINE IS REMOVED
    ports:
      - "8080:8080"
    networks:
      - overlay-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 3s
      retries: 5

  node-1:
    build: .
    container_name: overlay-node-1
    # command: ... <--- THIS LINE IS REMOVED
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - overlay-net

  # ... (remove the 'command' line from nodes 2 through 10 as well) ...

  node-10:
    build: .
    container_name: overlay-node-10
    # command: ... <--- THIS LINE IS REMOVED
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - overlay-net

  test-runner:
    build: .
    container_name: overlay-test-runner
    volumes:
      - ./test-scripts:/test-scripts
      - ./test-results:/test-results
    command: |
      bash -c "
        echo 'Waiting for all nodes to start...'
        sleep 10
        
        echo 'list-messaging-nodes' | nc registry 8080
        sleep 2
        
        echo 'setup-overlay 4' | nc registry 8080
        sleep 5
        
        echo 'send-overlay-link-weights' | nc registry 8080
        sleep 5
        
        echo 'start 100' | nc registry 8080
        sleep 30
        
        echo 'Test execution complete'
      "
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5
      - node-6
      - node-7
      - node-8
      - node-9
      - node-10
    networks:
      - overlay-net

networks:
  overlay-net:
    driver: bridge