package csx55.dfs.protocol;

public enum MessageType {
    MAJOR_HEARTBEAT,
    MINOR_HEARTBEAT,
    HEARTBEAT_RESPONSE,
    REQUEST_CHUNK_SERVERS_FOR_WRITE,
    REQUEST_CHUNK_SERVER_FOR_READ,
    CHUNK_SERVER_FOR_READ_RESPONSE,
    REQUEST_FILE_INFO,
    CHUNK_SERVERS_RESPONSE,
    FILE_INFO_RESPONSE,
    STORE_CHUNK_REQUEST,
    READ_CHUNK_REQUEST,
    CHUNK_DATA_RESPONSE,
    STORE_CHUNK_RESPONSE,
    REPLICATE_CHUNK_REQUEST,
    REPLICATE_CHUNK_RESPONSE,
    RECONSTRUCT_FRAGMENT_REQUEST,
    RECONSTRUCT_FRAGMENT_RESPONSE
}
