package csx55.pastry.transport;

public enum MessageType {
  REGISTER,
  REGISTER_RESPONSE,
  GET_RANDOM_NODE,
  RANDOM_NODE_RESPONSE,
  DEREGISTER,
  JOIN_REQUEST,
  JOIN_RESPONSE,
  ROUTING_TABLE_UPDATE,
  LEAF_SET_UPDATE,
  LOOKUP,
  LOOKUP_RESPONSE,
  STORE_FILE,
  RETRIEVE_FILE,
  FILE_DATA,
  ACK
}
