package csx55.sta.silver.config

object BusinessRules {
  val MORNING_RUSH_START = 7
  val MORNING_RUSH_END = 9
  val EVENING_RUSH_START = 16
  val EVENING_RUSH_END = 19
  val DISTANCE_SHORT_MAX = 1.0
  val DISTANCE_MEDIUM_MAX = 5.0
  val DISTANCE_LONG_MAX = 20.0
  val FARE_ECONOMY_MAX = 10.0
  val FARE_STANDARD_MAX = 30.0
  val FARE_PREMIUM_MAX = 100.0
  val SEVERE_PRECIPITATION_THRESHOLD = 1.0
  val SEVERE_WIND_SPEED_THRESHOLD = 30.0
  val TEMP_FREEZING_MAX = 32.0
  val TEMP_COLD_MAX = 50.0
  val TEMP_MILD_MAX = 70.0
  val TEMP_WARM_MAX = 85.0
  val PRECIP_LIGHT_MAX = 0.1
  val PRECIP_MODERATE_MAX = 0.5
  val WIND_CALM_MAX = 10.0
  val WIND_BREEZY_MAX = 20.0
  val WIND_WINDY_MAX = 30.0
  val HIGH_IMPACT_WIND_THRESHOLD = 50.0
  val MEDIUM_IMPACT_PRECIP_THRESHOLD = 0.5
  val EXTREME_COLD_THRESHOLD = 20.0
  val EXTREME_HOT_THRESHOLD = 95.0
  val MAJOR_EVENT_ATTENDANCE_THRESHOLD = 20000
  val MAJOR_SPORTS_CONCERT_THRESHOLD = 10000
  val EVENT_SMALL_MAX = 1000
  val EVENT_MEDIUM_MAX = 10000
  val EVENT_LARGE_MAX = 50000
  val DURATION_BRIEF_MAX = 2.0
  val DURATION_MODERATE_MAX = 6.0
  val DURATION_EXTENDED_MAX = 12.0
  val INCREMENTAL_GRACE_PERIOD_HOURS = 1
  val DEFAULT_WATERMARK_EPOCH = "1970-01-01 00:00:00"
}
